# docker-compose.yml文件的版本
version: "3"
# 管理的服务
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
      - "./mysql-files:/var/lib/mysql-files"
      - "./conf/my.cnf:/etc/mysql/my.cnf"
    environment:
      # 环境变量
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}